sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_ea9d87f0a16f_key -iv $encrypted_ea9d87f0a16f_iv -in k8s-gke-381909-2f161db2459f.json.enc -out k8s-gke-381909-2f161db2459f.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
